language: php
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable' SYMFONY_DEPRECATIONS_HELPER=max[total]=999999
    - php: 7.2
    - php: 7.3
      env: SYMFONY_VERSION='^3.3'
    - php: 7.3
      env: SYMFONY_VERSION='^4.0'
    - php: 7.3
      env: SYMFONY_VERSION='^5.0'
    - php: 7.4
      env: SYMFONY_VERSION='^5.0'
    - php: 7.4
      env: DEPENDENCIES='dev' SYMFONY_VERSION='5.1.*@dev'

before_install:
  - composer self-update
  - if [ "$DEPENDENCIES" == "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer --no-update require symfony/framework-bundle:${SYMFONY_VERSION}; fi;

install:
  - composer update $COMPOSER_FLAGS

script:
  - ./vendor/bin/phpunit
